<a href="https://colab.research.google.com/github/saurabhmungale/DataScience_Assignements/blob/main/Numpy_Asignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Que.1)1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.


In [1]:
import numpy as np

# Create a NumPy array of integers from 0 to 5
arr = np.arange(6)

# Print the array and its data type
print("Array:", arr)
print("Data type:", arr.dtype)


Array: [0 1 2 3 4 5]
Data type: int64


Que.2) Given a NumPy array 'arr', check if its data type is float64.arr = np.array([1.5, 2.6, 3.7])


In [2]:
import numpy as np

# Given NumPy array
arr = np.array([1.5, 2.6, 3.7])

# Check if the data type is float64
if arr.dtype == np.float64:
    print("The data type of the array is float64.")
else:
    print(f"The data type of the array is {arr.dtype}.")


The data type of the array is float64.


Que.3) Create a NumPy array 'arr' with a data type of complex128 containing three complex number

In [3]:
import numpy as np

# Given NumPy array
arr = np.array([1.5, 2.6, 3.7])

# Check if the data type is float64
if arr.dtype == np.float64:
    print("The data type of the array is float64.")
else:
    print(f"The data type of the array is {arr.dtype}.")


The data type of the array is float64.


QUe.4)Convert an existing NumPy array 'arr' of integers to float32 data type.

In [4]:
import numpy as np

# Existing NumPy array of integers
arr = np.array([1, 2, 3, 4, 5])

# Convert the array to float32 data type
arr_float32 = arr.astype(np.float32)

# Print the original and converted arrays
print("Original array:", arr)
print("Original array data type:", arr.dtype)
print("Converted array:", arr_float32)
print("Converted array data type:", arr_float32.dtype)


Original array: [1 2 3 4 5]
Original array data type: int64
Converted array: [1. 2. 3. 4. 5.]
Converted array data type: float32


Que.5)Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

In [5]:
import numpy as np

# Given NumPy array with float64 data type
arr = np.array([1.123456789, 2.987654321, 3.141592653], dtype=np.float64)

# Convert the array to float32 data type
arr_float32 = arr.astype(np.float32)

# Print the original and converted arrays
print("Original array:", arr)
print("Original array data type:", arr.dtype)
print("Converted array:", arr_float32)
print("Converted array data type:", arr_float32.dtype)


Original array: [1.12345679 2.98765432 3.14159265]
Original array data type: float64
Converted array: [1.1234568 2.9876542 3.1415927]
Converted array data type: float32


Que.6)Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data
type.

In [6]:
import numpy as np

def array_attributes(arr):
    """
    Returns the shape, size, and data type of a NumPy array.

    Parameters:
        arr (numpy.ndarray): Input NumPy array.

    Returns:
        tuple: A tuple containing the shape, size, and data type of the array.
    """
    return arr.shape, arr.size, arr.dtype

# Example usage:
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape, size, dtype = array_attributes(arr)

print(f"Array: \n{arr}")
print(f"Shape: {shape}")
print(f"Size: {size}")
print(f"Data Type: {dtype}")


Array: 
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Size: 6
Data Type: int64


Que.7)Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

In [7]:
import numpy as np

def array_dimension(arr):
    """
    Returns the dimensionality of a NumPy array.

    Parameters:
        arr (numpy.ndarray): Input NumPy array.

    Returns:
        int: Dimensionality of the array.
    """
    return arr.ndim

# Example usage:
arr_1d = np.array([1, 2, 3])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_3d = np.array([[[1], [2]], [[3], [4]]])

print(f"Dimensionality of arr_1d: {array_dimension(arr_1d)}")
print(f"Dimensionality of arr_2d: {array_dimension(arr_2d)}")
print(f"Dimensionality of arr_3d: {array_dimension(arr_3d)}")


Dimensionality of arr_1d: 1
Dimensionality of arr_2d: 2
Dimensionality of arr_3d: 3


Que.8)Design a function item_size_info that takes a NumPy array as input and returns the item size and the total
size in bytes.

In [8]:
import numpy as np

def item_size_info(arr):
    """
    Returns the item size and total size in bytes of a NumPy array.

    Parameters:
        arr (numpy.ndarray): Input NumPy array.

    Returns:
        tuple: A tuple containing the item size (in bytes) and total size (in bytes).
    """
    item_size = arr.itemsize  # Size of one element in bytes
    total_size = arr.nbytes   # Total size of the array in bytes
    return item_size, total_size

# Example usage:
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)

item_size, total_size = item_size_info(arr)
print(f"Array: \n{arr}")
print(f"Item size (in bytes): {item_size}")
print(f"Total size (in bytes): {total_size}")


Array: 
[[1 2 3]
 [4 5 6]]
Item size (in bytes): 4
Total size (in bytes): 24


Que.9)Create a function array_strides that takes a NumPy array as input and returns the strides of the array

In [9]:
import numpy as np

def array_strides(arr):
    """
    Returns the strides of a NumPy array.

    Parameters:
        arr (numpy.ndarray): Input NumPy array.

    Returns:
        tuple: A tuple containing the strides of the array.
    """
    return arr.strides

# Example usage:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]], dtype=np.float64)

print(f"Strides of arr_2d: {array_strides(arr_2d)}")
print(f"Strides of arr_3d: {array_strides(arr_3d)}")



Strides of arr_2d: (12, 4)
Strides of arr_3d: (32, 16, 8)


Que.10) Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape
and strides of the array.

In [10]:
import numpy as np

def shape_stride_relationship(arr):
    """
    Returns the shape and strides of a NumPy array.

    Parameters:
        arr (numpy.ndarray): Input NumPy array.

    Returns:
        tuple: A tuple containing the shape and strides of the array.
    """
    return arr.shape, arr.strides

# Example usage:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]], dtype=np.float64)

shape_2d, strides_2d = shape_stride_relationship(arr_2d)
shape_3d, strides_3d = shape_stride_relationship(arr_3d)

print(f"Shape of arr_2d: {shape_2d}, Strides: {strides_2d}")
print(f"Shape of arr_3d: {shape_3d}, Strides: {strides_3d}")


Shape of arr_2d: (2, 3), Strides: (12, 4)
Shape of arr_3d: (2, 2, 2), Strides: (32, 16, 8)


QUe.11)Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of
zeros with `n` elements.

In [11]:
import numpy as np

def create_zeros_array(n):
    """
    Creates a NumPy array of zeros with n elements.

    Parameters:
        n (int): Number of elements in the array.

    Returns:
        numpy.ndarray: A NumPy array filled with zeros.
    """
    return np.zeros(n)

# Example usage:
array_of_zeros = create_zeros_array(5)
print("Array of zeros:", array_of_zeros)
print("Shape:", array_of_zeros.shape)
print("Data type:", array_of_zeros.dtype)


Array of zeros: [0. 0. 0. 0. 0.]
Shape: (5,)
Data type: float64


Que.12) Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D
NumPy array filled with ones of size `rows x cols`.

In [12]:
import numpy as np

def create_ones_matrix(rows, cols):
    """
    Creates a 2D NumPy array filled with ones of size rows x cols.

    Parameters:
        rows (int): Number of rows in the matrix.
        cols (int): Number of columns in the matrix.

    Returns:
        numpy.ndarray: A 2D NumPy array filled with ones.
    """
    return np.ones((rows, cols))

# Example usage:
ones_matrix = create_ones_matrix(3, 4)
print("Matrix filled with ones:")
print(ones_matrix)
print("Shape:", ones_matrix.shape)
print("Data type:", ones_matrix.dtype)


Matrix filled with ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Shape: (3, 4)
Data type: float64


QUe.13) Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified
`step`.

In [13]:
import numpy as np

def generate_range_array(start, stop, step):
    """
    Generates a NumPy array with values from start to stop (exclusive),
    with the specified step size.

    Parameters:
        start (int): The starting value of the range.
        stop (int): The end value of the range (exclusive).
        step (int): The step size between values in the range.

    Returns:
        numpy.ndarray: A NumPy array containing the generated range of values.
    """
    return np.arange(start, stop, step)

# Example usage:
range_array = generate_range_array(2, 10, 2)
print("Generated range array:", range_array)


Generated range array: [2 4 6 8]


Que.13) Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified
`step`.

In [14]:
import numpy as np

def generate_range_array(start, stop, step):
    """
    Generates a NumPy array with values from start to stop (exclusive),
    with the specified step size.

    Parameters:
        start (int): The starting value of the range.
        stop (int): The end value of the range (exclusive).
        step (int): The step size between values in the range.

    Returns:
        numpy.ndarray: A NumPy array containing the generated range of values.
    """
    return np.arange(start, stop, step)

# Example usage:
range_array = generate_range_array(2, 10, 2)
print("Generated range array:", range_array)


Generated range array: [2 4 6 8]


Que.14)Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
arguments and generates a NumPy array with num equally spaced values between `start` and `stop`
(inclusive).

In [15]:
import numpy as np

def generate_linear_space(start, stop, num):
    """
    Generates a NumPy array with num equally spaced values between start and stop (inclusive).

    Parameters:
        start (float): The starting value of the range.
        stop (float): The ending value of the range (inclusive).
        num (int): The number of equally spaced values to generate.

    Returns:
        numpy.ndarray: A NumPy array containing the equally spaced values.
    """
    return np.linspace(start, stop, num)

# Example usage:
linear_space_array = generate_linear_space(1.0, 5.0, 5)
print("Generated linear space array:", linear_space_array)


Generated linear space array: [1. 2. 3. 4. 5.]


Que.15) Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square
identity matrix of size `n x n` using `numpy.eye`.

In [16]:
import numpy as np

def create_identity_matrix(n):
    """
    Creates an identity matrix of size n x n.

    Parameters:
        n (int): The size of the identity matrix.

    Returns:
        numpy.ndarray: A square identity matrix of size n x n.
    """
    return np.eye(n)

# Example usage:
identity_matrix = create_identity_matrix(4)
print("Generated identity matrix:")
print(identity_matrix)


Generated identity matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Que.16) Write a function that takes a Python list and converts it into a NumPy array

In [17]:
import numpy as np

def list_to_numpy_array(py_list):
    """
    Converts a Python list to a NumPy array.

    Parameters:
        py_list (list): A Python list to be converted.

    Returns:
        numpy.ndarray: The converted NumPy array.
    """
    return np.array(py_list)

# Example usage:
python_list = [1, 2, 3, 4, 5]
numpy_array = list_to_numpy_array(python_list)

print("Python list:", python_list)
print("Converted NumPy array:", numpy_array)


Python list: [1, 2, 3, 4, 5]
Converted NumPy array: [1 2 3 4 5]


Que.17)Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the
same data

In [18]:
import numpy as np

# Create a NumPy array
original_array = np.array([1, 2, 3, 4, 5])

# Use numpy.view to create a new array object sharing the same data
view_array = original_array.view()

# Modify the original array to show that the view_array reflects the changes
original_array[0] = 10

# Print both arrays to show they share the same data
print("Original array:", original_array)
print("View array:", view_array)


Original array: [10  2  3  4  5]
View array: [10  2  3  4  5]


Que.18)Write a function that takes two NumPy arrays and concatenates them along a specified axis.

In [20]:
import numpy as np

def concatenate_arrays(arr1, arr2, axis=0):
    """
    Concatenates two NumPy arrays along the specified axis.

    Parameters:
        arr1 (numpy.ndarray): The first array.
        arr2 (numpy.ndarray): The second array.
        axis (int, optional): The axis along which the arrays will be concatenated. Default is 0 (vertical).

    Returns:
        numpy.ndarray: The concatenated NumPy array.
    """
    return np.concatenate((arr1, arr2), axis=axis)

# Example usage:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Concatenate along axis 0 (rows)
result_axis_0 = concatenate_arrays(arr1, arr2, axis=0)
print("Concatenated along axis 0 (rows):")
print(result_axis_0)

# Concatenate along axis 1 (columns)
result_axis_1 = concatenate_arrays(arr1, arr2, axis=1)
print("Concatenated along axis 1:")

Concatenated along axis 0 (rows):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1:


Que.19) Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.

concatenate

In [21]:
import numpy as np

# Create two NumPy arrays with different shapes
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6, 7], [8, 9, 10]])

# Concatenate them horizontally (along axis 1)
result = np.concatenate((arr1, arr2), axis=1)

print("Array 1:")
print(arr1)
print("\nArray 2:")
print(arr2)
print("\nConcatenated array (horizontally):")
print(result)


Array 1:
[[1 2]
 [3 4]]

Array 2:
[[ 5  6  7]
 [ 8  9 10]]

Concatenated array (horizontally):
[[ 1  2  5  6  7]
 [ 3  4  8  9 10]]


QUe20)Write a function that vertically stacks multiple NumPy arrays given as a list.

In [22]:
import numpy as np

def vertical_stack(arrays):
    """
    Vertically stacks multiple NumPy arrays provided in a list.

    Parameters:
        arrays (list of numpy.ndarray): A list of NumPy arrays to be vertically stacked.

    Returns:
        numpy.ndarray: The vertically stacked NumPy array.
    """
    return np.vstack(arrays)

# Example usage:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr3 = np.array([[9, 10], [11, 12]])

# Stack the arrays vertically
result = vertical_stack([arr1, arr2, arr3])

print("Vertically stacked array:")
print(result)


Vertically stacked array:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


QUe.21)Write a Python function using NumPy to create an array of integers within a specified range (inclusive)
with a given step size

In [23]:
import numpy as np

def create_range_array(start, stop, step):
    """
    Creates a NumPy array of integers within a specified range (inclusive) with a given step size.

    Parameters:
        start (int): The starting integer of the range.
        stop (int): The ending integer of the range (inclusive).
        step (int): The step size between integers.

    Returns:
        numpy.ndarray: A NumPy array with integers in the specified range and step size.
    """
    return np.arange(start, stop + 1, step)

# Example usage:
range_array = create_range_array(1, 10, 2)

print("Generated range array:", range_array)


Generated range array: [1 3 5 7 9]


Que.22) Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1

In [24]:
import numpy as np

def create_range_array(start, stop, step):
    """
    Creates a NumPy array of integers within a specified range (inclusive) with a given step size.

    Parameters:
        start (int): The starting integer of the range.
        stop (int): The ending integer of the range (inclusive).
        step (int): The step size between integers.

    Returns:
        numpy.ndarray: A NumPy array with integers in the specified range and step size.
    """
    return np.arange(start, stop + 1, step)

# Example usage:
range_array = create_range_array(1, 10, 2)

print("Generated range array:", range_array)


Generated range array: [1 3 5 7 9]


Que.23 Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and
1000 (inclusive))

In [25]:
import numpy as np

def generate_log_spaced_values(start, stop, num_values):
    """
    Generates an array of logarithmically spaced values between start and stop.

    Parameters:
        start (float): The starting value of the range.
        stop (float): The ending value of the range.
        num_values (int): The number of logarithmically spaced values to generate.

    Returns:
        numpy.ndarray: An array of logarithmically spaced values.
    """
    return np.logspace(np.log10(start), np.log10(stop), num_values)

# Example usage:
log_values = generate_log_spaced_values(1, 1000, 5)

print("Generated array of logarithmically spaced values:", log_values)


Generated array of logarithmically spaced values: [   1.            5.62341325   31.6227766   177.827941   1000.        ]


Que.24) Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values
are random integers between 1 and 100.

In [26]:
import numpy as np
import pandas as pd

def create_dataframe():
    # Generate a NumPy array with 5 rows and 3 columns of random integers between 1 and 100
    data = np.random.randint(1, 101, size=(5, 3))

    # Create a Pandas DataFrame using the NumPy array
    df = pd.DataFrame(data, columns=['A', 'B', 'C'])

    return df

# Example usage:
df = create_dataframe()

print("Pandas DataFrame with random integers:")
print(df)


Pandas DataFrame with random integers:
    A   B   C
0   6  75  84
1  31   1  86
2  82  32  18
3   3  93  55
4  98  79  93


Que.25) Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column
with zeros. Use NumPy operations within the Pandas DataFrame.

In [27]:
import pandas as pd
import numpy as np

def replace_negative_with_zero(df, column_name):
    """
    Replaces all negative values in the specified column of a DataFrame with zeros.

    Parameters:
        df (pandas.DataFrame): The input DataFrame.
        column_name (str): The column in which to replace negative values with zeros.

    Returns:
        pandas.DataFrame: The modified DataFrame with negative values replaced by zeros.
    """
    # Use NumPy to replace negative values in the specified column with zeros
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])

    return df

# Example usage:
data = {
    'A': [1, -2, 3, -4, 5],
    'B': [-10, 20, -30, 40, -50],
    'C': [100, -200, 300, -400, 500]
}

# Create a Pandas DataFrame
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

# Replace negative values in column 'B' with zeros
df_modified = replace_negative_with_zero(df, 'B')

print("\nModified DataFrame (negative values in column 'B' replaced with zeros):")
print(df_modified)



Original DataFrame:
   A   B    C
0  1 -10  100
1 -2  20 -200
2  3 -30  300
3 -4  40 -400
4  5 -50  500

Modified DataFrame (negative values in column 'B' replaced with zeros):
   A   B    C
0  1   0  100
1 -2  20 -200
2  3   0  300
3 -4  40 -400
4  5   0  500


Que.26)Access the 3rd element from the given NumPy array.arr = np.array([10, 20, 30, 40, 50])



In [28]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Accessing the 3rd element (index 2)
third_element = arr[2]

print("The 3rd element is:", third_element)


The 3rd element is: 30


Que.27) Retrieve the element at index (1, 2) from the 2D NumPy array.arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [29]:
import numpy as np

# Creating the 2D NumPy array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Retrieving the element at index (1, 2)
element = arr_2d[1, 2]

print("The element at index (1, 2) is:", element)


The element at index (1, 2) is: 6


Que.28)Using boolean indexing, extract elements greater than 5 from the given NumPy array.arr = np.array([3, 8, 2, 10, 5, 7])


In [30]:
import numpy as np

# Creating the NumPy array
arr = np.array([3, 8, 2, 10, 5, 7])

# Using boolean indexing to extract elements greater than 5
filtered_elements = arr[arr > 5]

print("Elements greater than 5:", filtered_elements)


Elements greater than 5: [ 8 10  7]


QUe.29)Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [31]:
import numpy as np

# Creating the NumPy array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Slicing to extract elements from index 2 to 5 (inclusive)
sliced_elements = arr[2:6]

print("Extracted elements from index 2 to 5:", sliced_elements)


Extracted elements from index 2 to 5: [3 4 5 6]


Que,30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [32]:
import numpy as np

# Creating the 2D NumPy array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Slicing to extract the sub-array [[2, 3], [5, 6]]
sub_array = arr_2d[1:3, 0:2]

print("Extracted sub-array:")
print(sub_array)


Extracted sub-array:
[[4 5]
 [7 8]]


QUe.31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices
provided in another array

In [33]:
import numpy as np

def extract_elements_by_indices(arr_2d, indices):
    """
    Extract elements from a 2D array based on given row and column indices.

    Parameters:
        arr_2d (numpy.ndarray): The 2D input NumPy array.
        indices (numpy.ndarray): An array of tuples, where each tuple is (row_index, column_index).

    Returns:
        numpy.ndarray: Array of extracted elements based on the provided indices.
    """
    # Unzip the indices into row and column arrays
    row_indices, col_indices = zip(*indices)

    # Convert row and column indices to numpy arrays for indexing
    row_indices = np.array(row_indices)
    col_indices = np.array(col_indices)

    # Use advanced indexing to extract elements from the 2D array
    extracted_elements = arr_2d[row_indices, col_indices]

    return extracted_elements

# Example usage:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Indices (row, column) where we want to extract elements
indices = [(0, 2), (1, 1), (2, 0)]  # Extract elements at (0, 2), (1, 1), (2, 0)

# Extract elements based on indices
result = extract_elements_by_indices(arr_2d, indices)

print("Extracted elements:", result)


Extracted elements: [3 5 7]


Que.32) Create a NumPy function that filters elements greater than a threshold from a given 1D array using
boolean indexing.

In [34]:
import numpy as np

def filter_elements_by_threshold(arr, threshold):
    """
    Filters elements from the 1D array that are greater than the given threshold.

    Parameters:
        arr (numpy.ndarray): The input 1D NumPy array.
        threshold (float or int): The threshold value to compare elements.

    Returns:
        numpy.ndarray: A 1D array containing elements greater than the threshold.
    """
    # Apply boolean indexing to filter elements greater than the threshold
    filtered_elements = arr[arr > threshold]

    return filtered_elements

# Example usage:
arr = np.array([1, 5, 8, 3, 10, 12, 4])
threshold = 5

# Filter elements greater than the threshold
result = filter_elements_by_threshold(arr, threshold)

print("Filtered elements greater than threshold:", result)


Filtered elements greater than threshold: [ 8 10 12]


Que.33)Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three
separate arrays for each dimension.

In [36]:
import numpy as np

def extract_elements_from_3d_array(arr_3d, row_indices, col_indices, depth_indices):
    """
    Extracts specific elements from a 3D array using indices provided for each dimension.

    Parameters:
        arr_3d (numpy.ndarray): The input 3D NumPy array.
        row_indices (numpy.ndarray or list): Array or list of row indices.
        col_indices (numpy.ndarray or list): Array or list of column indices.
        depth_indices (numpy.ndarray or list): Array or list of depth indices.

    Returns:
        numpy.ndarray: Array of extracted elements.
    """
    # Using advanced indexing to extract elements from the 3D array
    extracted_elements = arr_3d[row_indices, col_indices, depth_indices]

    return extracted_elements

# Example usage:
arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                   [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
                   [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])

# Indices for the 3 dimensions (row, column, depth)
row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 0])
depth_indices = np.array([2, 0, 1])

# Extract elements from the 3D array based on the indices
result = extract_elements_from_3d_array(arr_3d, row_indices, col_indices, depth_indices)

print("Extracted elements:", result)


Extracted elements: [ 6 16 20]


QUe.34)Write a NumPy function that returns elements from an array where both two conditions are satisfied
using boolean indexing

In [37]:
import numpy as np

def filter_elements_with_conditions(arr, condition1, condition2):
    """
    Filters elements from the array where both conditions are satisfied using boolean indexing.

    Parameters:
        arr (numpy.ndarray): The input NumPy array.
        condition1 (numpy.ndarray): The first condition to filter the elements.
        condition2 (numpy.ndarray): The second condition to filter the elements.

    Returns:
        numpy.ndarray: Array containing elements where both conditions are satisfied.
    """
    # Applying both conditions using logical AND (&)
    filtered_elements = arr[condition1 & condition2]

    return filtered_elements

# Example usage:
arr = np.array([1, 5, 8, 3, 10, 12, 4])

# Define the two conditions
condition1 = arr > 5  # Elements greater than 5
condition2 = arr % 2 == 0  # Elements that are even

# Filter elements where both conditions are satisfied
result = filter_elements_with_conditions(arr, condition1, condition2)

print("Filtered elements where both conditions are satisfied:", result)


Filtered elements where both conditions are satisfied: [ 8 10 12]


Que.35)Create a NumPy function that extracts elements from a 2D array using row and column indices provided
in separate arrays.

In [38]:
import numpy as np

def extract_elements_from_2d_array(arr_2d, row_indices, col_indices):
    """
    Extracts elements from a 2D array using row and column indices provided in separate arrays.

    Parameters:
        arr_2d (numpy.ndarray): The input 2D NumPy array.
        row_indices (numpy.ndarray or list): Array or list of row indices.
        col_indices (numpy.ndarray or list): Array or list of column indices.

    Returns:
        numpy.ndarray: Array of extracted elements based on the provided indices.
    """
    # Use advanced indexing to extract elements using row and column indices
    extracted_elements = arr_2d[row_indices, col_indices]

    return extracted_elements

# Example usage:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Row and column indices for extraction
row_indices = np.array([0, 1, 2])  # Row indices
col_indices = np.array([2, 1, 0])  # Column indices

# Extract elements from the 2D array based on the indices
result = extract_elements_from_2d_array(arr_2d, row_indices, col_indices)

print("Extracted elements:", result)


Extracted elements: [3 5 7]


QUe.36)Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.


In [39]:
import numpy as np

# Create a 3x3 array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Scalar value to add
scalar = 5

# Add the scalar to each element using broadcasting
result = arr + scalar

print("Resulting array after adding scalar:")
print(result)


Resulting array after adding scalar:
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


QUe.37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the
corresponding element in arr1 using NumPy broadcasting

In [41]:
import numpy as np

# Define arr1 and arr2
arr1 = np.array([[1, 2, 3]])  # Shape (1, 3)
arr2 = np.array([[4, 5, 6, 7],
                 [8, 9, 10, 11],
                 [12, 13, 14, 15]])  # Shape (3, 4)

# Transpose arr1 to make its shape (3, 1) for broadcasting compatibility
arr1_transposed = arr1.T

# Multiply each row of arr2 by the corresponding element in arr1 using broadcasting
result = arr2 * arr1_transposed # Now the shapes are compatible for broadcasting: (3, 4) * (3, 1)

print("Resulting array after broadcasting multiplication:")
print(result)

Resulting array after broadcasting multiplication:
[[ 4  5  6  7]
 [16 18 20 22]
 [36 39 42 45]]


QUe.38) Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using
NumPy broadcasting

In [42]:
import numpy as np

# Define arr1 and arr2
arr1 = np.array([[1, 2, 3, 4]])  # Shape (1, 4)
arr2 = np.array([[5, 6, 7],
                 [8, 9, 10],
                 [11, 12, 13],
                 [14, 15, 16]])  # Shape (4, 3)

# Reshape arr1 to be a (4, 1) array and add it to arr2 using broadcasting
arr1_reshaped = arr1.T  # Transpose arr1 to shape (4, 1)
result = arr2 + arr1_reshaped

print("Resulting array after broadcasting addition:")
print(result)


Resulting array after broadcasting addition:
[[ 6  7  8]
 [10 11 12]
 [14 15 16]
 [18 19 20]]


Que.39). Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy
broadcasting.

In [43]:
import numpy as np

# Define arr1 and arr2
arr1 = np.array([[1], [2], [3]])  # Shape (3, 1)
arr2 = np.array([[4, 5, 6]])  # Shape (1, 3)

# Add arr1 and arr2 using broadcasting
result = arr1 + arr2

print("Resulting array after broadcasting addition:")
print(result)


Resulting array after broadcasting addition:
[[5 6 7]
 [6 7 8]
 [7 8 9]]


Que,.40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy
broadcasting. Handle the shape incompatibility.

In [44]:
import numpy as np

# Define arr1 and arr2
arr1 = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2, 3)
arr2 = np.array([[7, 8], [9, 10]])  # Shape (2, 2)

# Reshape arr2 to make it compatible for broadcasting
arr2_reshaped = arr2[:, :, np.newaxis]  # Shape (2, 2, 1)

# Now we can multiply using broadcasting
result = arr1 * arr2_reshaped

print("Resulting array after broadcasting multiplication:")
print(result)



Resulting array after broadcasting multiplication:
[[[ 7 14 21]
  [32 40 48]]

 [[ 9 18 27]
  [40 50 60]]]


Que.41)Calculate column wise mean for the given arrayarr = np.array([[1, 2, 3], [4, 5, 6]])


In [45]:
import numpy as np

# Define the array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Calculate the column-wise mean (mean along axis 0)
column_wise_mean = np.mean(arr, axis=0)

print("Column-wise mean:")
print(column_wise_mean)


Column-wise mean:
[2.5 3.5 4.5]


Que.42. Find maximum value in each row of the given array:arr = np.array([[1, 2, 3], [4, 5, 6]])


In [46]:
import numpy as np

# Define the array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Calculate the column-wise mean (mean along axis 0)
column_wise_mean = np.mean(arr, axis=0)

print("Column-wise mean:")
print(column_wise_mean)


Column-wise mean:
[2.5 3.5 4.5]


Que.43. For the given array, find indices of maximum value in each column.arr = np.array([[1, 2, 3], [4, 5, 6]])


In [47]:
import numpy as np

# Define the array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Find indices of the maximum value in each column
max_indices = np.argmax(arr, axis=0)

print("Indices of maximum value in each column:")
print(max_indices)


Indices of maximum value in each column:
[1 1 1]


Que.44) For the given array, apply custom function to calculate moving sum along rows.arr = np.array([[1, 2, 3], [4, 5, 6]])



In [48]:
import numpy as np

# Define the array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Define the custom moving sum function (with window size 2 as an example)
def moving_sum(arr, window_size=2):
    # Apply convolve with 'valid' mode to avoid boundary issues
    return np.convolve(arr, np.ones(window_size), mode='valid')

# Apply the moving sum along each row
result = np.apply_along_axis(moving_sum, axis=1, arr=arr)

print("Moving sum along rows:")
print(result)


Moving sum along rows:
[[ 3.  5.]
 [ 9. 11.]]


Que.45. In the given array, check if all elements in each column are even.arr = np.array([[2, 4, 6], [3, 5, 7]])

In [49]:
import numpy as np

# Define the array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Define the custom moving sum function (with window size 2 as an example)
def moving_sum(arr, window_size=2):
    # Apply convolve with 'valid' mode to avoid boundary issues
    return np.convolve(arr, np.ones(window_size), mode='valid')

# Apply the moving sum along each row
result = np.apply_along_axis(moving_sum, axis=1, arr=arr)

print("Moving sum along rows:")
print(result)


Moving sum along rows:
[[ 3.  5.]
 [ 9. 11.]]


QUe.46. Given a NumPy array arr, reshape it into a matrix of dimensions m rows and n columns. Return the
reshaped matrix.original_array = np.array([1, 2, 3, 4, 5, 6])

In [50]:
import numpy as np

# Define the original array
original_array = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array into a matrix with m rows and n columns
m, n = 2, 3  # Example: 2 rows and 3 columns
reshaped_matrix = original_array.reshape(m, n)

print("Reshaped Matrix:")
print(reshaped_matrix)


Reshaped Matrix:
[[1 2 3]
 [4 5 6]]


Que.47. Create a function that takes a matrix as input and returns the flattened array.input_matrix = np.array([[1, 2, 3], [4, 5, 6]])


In [51]:
import numpy as np

# Define the function to flatten the matrix
def flatten_matrix(matrix):
    return matrix.flatten()

# Define the input matrix
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

# Call the function to flatten the matrix
flattened_array = flatten_matrix(input_matrix)

print("Flattened Array:")
print(flattened_array)


Flattened Array:
[1 2 3 4 5 6]


Que.48. Write a function that concatenates two given arrays along a specified axis.array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])


In [52]:
import numpy as np

# Define the function to concatenate arrays along a specified axis
def concatenate_arrays(array1, array2, axis):
    return np.concatenate((array1, array2), axis=axis)

# Define the input arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Call the function to concatenate along axis 0 (vertically)
result_axis0 = concatenate_arrays(array1, array2, axis=0)

# Call the function to concatenate along axis 1 (horizontally)
result_axis1 = concatenate_arrays(array1, array2, axis=1)

print("Concatenated along axis 0 (vertical):")
print(result_axis0)

print("Concatenated along axis 1 (horizontal):")
print(result_axis1)


Concatenated along axis 0 (vertical):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1 (horizontal):
[[1 2 5 6]
 [3 4 7 8]]


QUe.49. Create a function that splits an array into multiple sub-arrays along a specified axis.original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])



In [53]:
import numpy as np

# Define the function to split an array along a specified axis
def split_array(array, axis, num_splits):
    return np.split(array, num_splits, axis=axis)

# Define the original array
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Call the function to split the array along axis 0 (vertical split)
result_axis0 = split_array(original_array, axis=0, num_splits=3)

# Call the function to split the array along axis 1 (horizontal split)
result_axis1 = split_array(original_array, axis=1, num_splits=3)

print("Splitted along axis 0:")
for sub_array in result_axis0:
    print(sub_array)

print("\nSplitted along axis 1:")
for sub_array in result_axis1:
    print(sub_array)


Splitted along axis 0:
[[1 2 3]]
[[4 5 6]]
[[7 8 9]]

Splitted along axis 1:
[[1]
 [4]
 [7]]
[[2]
 [5]
 [8]]
[[3]
 [6]
 [9]]


QUE.50. Write a function that inserts and then deletes elements from a given array at specified indices.original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

In [54]:
import numpy as np

# Define the function to insert and delete elements in the array
def insert_and_delete_elements(array, indices_to_insert, values_to_insert, indices_to_delete):
    # Insert elements at the specified indices
    array_after_insert = np.insert(array, indices_to_insert, values_to_insert)

    # Delete elements at the specified indices
    array_after_delete = np.delete(array_after_insert, indices_to_delete)

    return array_after_insert, array_after_delete

# Define the original array, indices, and values
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

# Call the function
array_after_insert, array_after_delete = insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)

# Print the results
print("Array after insertion:")
print(array_after_insert)

print("\nArray after deletion:")
print(array_after_delete)


Array after insertion:
[ 1  2 10  3  4 11  5]

Array after deletion:
[ 1 10  4 11  5]


Que.51)Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.
Perform element-wise addition between `arr1` and `arr2`.

In [55]:
import numpy as np

# Create arr1 with random integers (size 5 for example)
arr1 = np.random.randint(1, 10, size=5)

# Create arr2 with integers from 1 to 10 (size 5)
arr2 = np.arange(1, 6)

# Perform element-wise addition
result = arr1 + arr2

# Print the arrays and the result
print("arr1:", arr1)
print("arr2:", arr2)
print("Element-wise addition result:", result)


arr1: [4 8 3 2 1]
arr2: [1 2 3 4 5]
Element-wise addition result: [ 5 10  6  6  6]


QUe.52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers
from 1 to 10. Subtract `arr2` from `arr1` element-wise

In [56]:
import numpy as np

# Create arr1 with sequential integers from 10 to 1
arr1 = np.arange(10, 0, -1)

# Create arr2 with integers from 1 to 10
arr2 = np.arange(1, 11)

# Perform element-wise subtraction (arr1 - arr2)
result = arr1 - arr2

# Print the arrays and the result
print("arr1:", arr1)
print("arr2:", arr2)
print("Element-wise subtraction result:", result)


arr1: [10  9  8  7  6  5  4  3  2  1]
arr2: [ 1  2  3  4  5  6  7  8  9 10]
Element-wise subtraction result: [ 9  7  5  3  1 -1 -3 -5 -7 -9]


Que.53) Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.
Perform element-wise multiplication between `arr1` and `arr2`.

In [58]:
import numpy as np

# Create arr1 with random integers (size 5 for example)
arr1 = np.random.randint(1, 10, size=5)

# Create arr2 with integers from 1 to 5
arr2 = np.arange(1, 6)

# Perform element-wise multiplication
result = arr1 * arr2

# Print the arrays and the result
print("arr1:", arr1)
print("arr2:", arr2)
print("Element-wise multiplication result:", result)


arr1: [2 5 8 1 1]
arr2: [1 2 3 4 5]
Element-wise multiplication result: [ 2 10 24  4  5]


QUe.54)Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1
to 5. Perform element-wise division of `arr1` by `arr2`.

In [59]:
import numpy as np

# Create arr1 with even integers from 2 to 10
arr1 = np.arange(2, 11, 2)

# Create arr2 with integers from 1 to 5
arr2 = np.arange(1, 6)

# Perform element-wise division
result = arr1 / arr2

# Print the arrays and the result
print("arr1:", arr1)
print("arr2:", arr2)
print("Element-wise division result:", result)


arr1: [ 2  4  6  8 10]
arr2: [1 2 3 4 5]
Element-wise division result: [2. 2. 2. 2. 2.]


QUe.55)Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

In [60]:
import numpy as np

# Create arr1 with integers from 1 to 5
arr1 = np.arange(1, 6)

# Create arr2 with the same numbers reversed
arr2 = arr1[::-1]

# Perform element-wise exponentiation (arr1 raised to the power of arr2)
result = arr1 ** arr2

# Print the arrays and the result
print("arr1:", arr1)
print("arr2:", arr2)
print("Element-wise exponentiation result:", result)


arr1: [1 2 3 4 5]
arr2: [5 4 3 2 1]
Element-wise exponentiation result: [ 1 16 27 16  5]


QUe.56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])


In [61]:
import numpy as np

# Function to count occurrences of a substring in a NumPy array of strings
def count_substring_occurrences(arr, substring):
    # Use np.char.count() to count occurrences of the substring in each element
    count_array = np.char.count(arr, substring)

    # Return the total count by summing up the count array
    return np.sum(count_array)

# Example array of strings
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

# Substring to search for
substring = 'hello'

# Get the count of occurrences
count = count_substring_occurrences(arr, substring)

# Print the result
print(f"The substring '{substring}' occurs {count} times in the array.")


The substring 'hello' occurs 3 times in the array.


QUe.57. Write a function that extracts uppercase characters from a NumPy array of strings.

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])




In [62]:
import numpy as np

# Function to extract uppercase characters from a NumPy array of strings
def extract_uppercase_chars(arr):
    # Initialize an empty list to store the uppercase characters
    uppercase_chars = []

    # Iterate over each string in the array
    for string in arr:
        # Use list comprehension to filter out uppercase characters from each string
        uppercase_chars.append(''.join([char for char in string if char.isupper()]))

    # Convert the list of uppercase characters into a NumPy array
    return np.array(uppercase_chars)

# Example array of strings
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

# Extract uppercase characters
result = extract_uppercase_chars(arr)

# Print the result
print("Extracted uppercase characters:", result)


Extracted uppercase characters: ['H' 'W' 'OAI' 'GPT']


Que.58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [63]:
import numpy as np

# Function to replace occurrences of a substring with a new string in a NumPy array of strings
def replace_substring(arr, old_substring, new_substring):
    # Use np.char.replace() to replace the old substring with the new substring
    return np.char.replace(arr, old_substring, new_substring)

# Example array of strings
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

# Substring to replace and the new string
old_substring = 'apple'
new_substring = 'orange'

# Replace occurrences of old_substring with new_substring
result = replace_substring(arr, old_substring, new_substring)

# Print the result
print("Array after replacement:", result)


Array after replacement: ['orange' 'banana' 'grape' 'pineorange']


Que.59. Write a function that concatenates strings in a NumPy array element-wise.arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

In [64]:
import numpy as np

# Function to concatenate strings in two NumPy arrays element-wise
def concatenate_strings(arr1, arr2):
    # Use np.char.add() to concatenate corresponding elements of the two arrays
    return np.char.add(arr1, arr2)

# Example arrays of strings
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

# Concatenate the strings element-wise
result = concatenate_strings(arr1, arr2)

# Print the result
print("Concatenated array:", result)


Concatenated array: ['HelloOpen' 'WorldAI']


Que.60. Write a function that finds the length of the longest string in a NumPy array.arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [65]:
import numpy as np

# Function to find the length of the longest string in a NumPy array
def longest_string_length(arr):
    # Use np.char.str_len() to find the length of each string
    string_lengths = np.char.str_len(arr)

    # Use np.max() to find the maximum length
    return np.max(string_lengths)

# Example array of strings
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

# Find the length of the longest string
result = longest_string_length(arr)

# Print the result
print("Length of the longest string:", result)


Length of the longest string: 9


Que,61,. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
standard deviation of the dataset using NumPy's functions

In [66]:
import numpy as np

# Create a dataset of 100 random integers between 1 and 1000
dataset = np.random.randint(1, 1001, 100)

# Compute the mean, median, variance, and standard deviation
mean = np.mean(dataset)
median = np.median(dataset)
variance = np.var(dataset)
std_deviation = np.std(dataset)

# Print the results
print(f"Mean: {mean}")
print(f"Median: {median}")
print(f"Variance: {variance}")
print(f"Standard Deviation: {std_deviation}")


Mean: 456.56
Median: 431.0
Variance: 76364.32639999999
Standard Deviation: 276.3409604094188


Que.62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the
dataset.

In [67]:
import numpy as np

# Generate an array of 50 random numbers between 1 and 100
dataset = np.random.randint(1, 101, 50)

# Find the 25th and 75th percentiles
percentile_25 = np.percentile(dataset, 25)
percentile_75 = np.percentile(dataset, 75)

# Print the results
print(f"25th Percentile: {percentile_25}")
print(f"75th Percentile: {percentile_75}")


25th Percentile: 18.5
75th Percentile: 70.5


QUe.63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these
arrays using NumPy's `corrcoef` function.

In [68]:
import numpy as np

# Create two arrays representing two sets of variables
array1 = np.array([10, 20, 30, 40, 50])
array2 = np.array([5, 15, 25, 35, 45])

# Compute the correlation coefficient matrix
correlation_matrix = np.corrcoef(array1, array2)

# Extract the correlation coefficient from the matrix
correlation_coefficient = correlation_matrix[0, 1]

# Print the result
print(f"Correlation Coefficient: {correlation_coefficient}")



Correlation Coefficient: 1.0


Que.64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.

In [69]:
import numpy as np

# Create two matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Perform matrix multiplication using np.dot
result = np.dot(matrix1, matrix2)

# Print the result
print("Matrix Multiplication Result:")
print(result)


Matrix Multiplication Result:
[[19 22]
 [43 50]]


Que.65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th
percentiles along with the first and third quartiles.

In [70]:
import numpy as np

# Create an array of 50 integers between 10 and 1000
array = np.random.randint(10, 1001, 50)

# Calculate the required percentiles and quartiles
percentile_10 = np.percentile(array, 10)
percentile_50 = np.percentile(array, 50)  # This is the median
percentile_90 = np.percentile(array, 90)
quartile_25 = np.percentile(array, 25)
quartile_75 = np.percentile(array, 75)

# Print the results
print(f"10th Percentile: {percentile_10}")
print(f"50th Percentile (Median): {percentile_50}")
print(f"90th Percentile: {percentile_90}")
print(f"1st Quartile (25th Percentile): {quartile_25}")
print(f"3rd Quartile (75th Percentile): {quartile_75}")


10th Percentile: 99.80000000000001
50th Percentile (Median): 459.5
90th Percentile: 779.0000000000001
1st Quartile (25th Percentile): 234.75
3rd Quartile (75th Percentile): 678.75


Que.66. Create a NumPy array of integers and find the index of a specific element.

In [71]:
import numpy as np

# Create a NumPy array of integers
arr = np.array([10, 20, 30, 40, 50, 60])

# Specify the element whose index you want to find
element = 40

# Use np.where() to find the index of the element
index = np.where(arr == element)[0]

# Print the result
print(f"Index of element {element}: {index}")


Index of element 40: [3]


Que.67. Generate a random NumPy array and sort it in ascending orde

In [72]:
import numpy as np

# Generate a random NumPy array with integers between 1 and 100
arr = np.random.randint(1, 101, 10)  # 10 random integers between 1 and 100

# Sort the array in ascending order
sorted_arr = np.sort(arr)

# Print the original and sorted arrays
print(f"Original Array: {arr}")
print(f"Sorted Array (Ascending): {sorted_arr}")


Original Array: [75 34 35 12 19 77 51 10 27 48]
Sorted Array (Ascending): [10 12 19 27 34 35 48 51 75 77]


Qyue.68. Filter elements >20  in the given NumPy array  arr = np.array([12, 25, 6, 42, 8, 30])


In [73]:
import numpy as np

# Given NumPy array
arr = np.array([12, 25, 6, 42, 8, 30])

# Filter elements greater than 20
filtered_arr = arr[arr > 20]

# Print the filtered array
print(f"Filtered Array (elements > 20): {filtered_arr}")


Filtered Array (elements > 20): [25 42 30]


Que.69. Filter elements which are divisible by 3 from a given NumPy array.arr = np.array([1, 5, 8, 12, 15])


In [74]:
import numpy as np

# Given NumPy array
arr = np.array([1, 5, 8, 12, 15])

# Filter elements divisible by 3
filtered_arr = arr[arr % 3 == 0]

# Print the filtered array
print(f"Filtered Array (divisible by 3): {filtered_arr}")


Filtered Array (divisible by 3): [12 15]


QUe.70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.arr = np.array([10, 20, 30, 40, 50])


In [75]:
import numpy as np

# Given NumPy array
arr = np.array([10, 20, 30, 40, 50])

# Filter elements ≥ 20 and ≤ 40
filtered_arr = arr[(arr >= 20) & (arr <= 40)]

# Print the filtered array
print(f"Filtered Array (elements ≥ 20 and ≤ 40): {filtered_arr}")


Filtered Array (elements ≥ 20 and ≤ 40): [20 30 40]


Que.71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.arr = np.array([1, 2, 3])


In [76]:
import numpy as np

# Given NumPy array
arr = np.array([1, 2, 3])

# Check byte order
byte_order = arr.dtype.byteorder

# Print the byte order
print(f"Byte order of the array: {byte_order}")


Byte order of the array: =


Que.72. For the given NumPy array, perform byte swapping in place using `byteswap()`.arr = np.array([1, 2, 3], dtype=np.int32)


In [77]:
import numpy as np

# Given NumPy array with dtype as np.int32
arr = np.array([1, 2, 3], dtype=np.int32)

# Perform byte swapping in place
arr.byteswap(True)

# Print the modified array
print(f"Array after byte swapping: {arr}")


Array after byte swapping: [16777216 33554432 50331648]


QUe.

73. For the given NumPy array, swap its byte order without modifying the original array using
newbyteorder().arr = np.array([1, 2, 3], dtype=np.int32)



In [78]:
import numpy as np

# Given NumPy array with dtype as np.int32
arr = np.array([1, 2, 3], dtype=np.int32)

# Swap byte order without modifying the original array
swapped_arr = arr.newbyteorder()

# Print the original and swapped arrays
print(f"Original array: {arr}")
print(f"Array with swapped byte order: {swapped_arr}")


Original array: [1 2 3]
Array with swapped byte order: [16777216 33554432 50331648]


QUe. 74. For the given NumPy array and swap its byte order conditionally based on system endianness using newbyteorder().arr = np.array([1, 2, 3], dtype=np.int32)

In [79]:
import numpy as np
import sys

# Given NumPy array with dtype as np.int32
arr = np.array([1, 2, 3], dtype=np.int32)

# Check the system's byte order
if sys.byteorder == 'little':
    # If the system is little-endian, swap to big-endian
    swapped_arr = arr.newbyteorder('>')
else:
    # If the system is big-endian, swap to little-endian
    swapped_arr = arr.newbyteorder('<')

# Print the original and swapped arrays
print(f"Original array: {arr}")
print(f"Array with swapped byte order: {swapped_arr}")


Original array: [1 2 3]
Array with swapped byte order: [16777216 33554432 50331648]


Que.75)For the given NumPy array, check if byte swapping is necessary for the current system using dtype
attribute byteorder.arr = np.array([1, 2, 3], dtype=np.int32)



In [80]:
import numpy as np
import sys

# Given NumPy array with dtype as np.int32
arr = np.array([1, 2, 3], dtype=np.int32)

# Check the byte order of the array and the system's native byte order
if arr.dtype.byteorder != sys.byteorder:
    print("Byte swapping is necessary.")
else:
    print("Byte swapping is not necessary.")


Byte swapping is necessary.


Que.76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify
an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

In [81]:
import numpy as np

# Create a NumPy array arr1 with values from 1 to 10
arr1 = np.arange(1, 11)

# Create a copy of arr1
arr2 = np.copy(arr1)

# Display both arrays
print("arr1:", arr1)
print("arr2 (copy of arr1):", arr2)


arr1: [ 1  2  3  4  5  6  7  8  9 10]
arr2 (copy of arr1): [ 1  2  3  4  5  6  7  8  9 10]


Que.77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from
the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

In [82]:
import numpy as np

# Create a 2D NumPy array 'matrix' of shape (3, 3) with random integers
matrix = np.random.randint(1, 10, size=(3, 3))

# Extract a slice (view) from the matrix
view_slice = matrix[1:, 1:]  # Extracting the bottom-right 2x2 slice

# Display the original matrix and the view slice
print("Original matrix:\n", matrix)
print("View slice:\n", view_slice)

# Modify an element in the view_slice
view_slice[0, 0] = 999

# Display the modified view_slice and the original matrix to observe the effect
print("\nModified view slice:\n", view_slice)
print("Original matrix after modification:\n", matrix)


Original matrix:
 [[3 5 8]
 [2 6 8]
 [4 2 9]]
View slice:
 [[6 8]
 [2 9]]

Modified view slice:
 [[999   8]
 [  2   9]]
Original matrix after modification:
 [[  3   5   8]
 [  2 999   8]
 [  4   2   9]]


Que.78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
`view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

In [83]:
import numpy as np

# Create a 4x3 NumPy array 'array_a' with sequential integers from 1 to 12
array_a = np.arange(1, 13).reshape(4, 3)

# Extract a slice (view) 'view_b' from 'array_a'
view_b = array_a[1:, 1:]  # Extracting a 3x2 slice from array_a

# Display the original array and the view slice before modification
print("Original array_a:\n", array_a)
print("View b:\n", view_b)

# Broadcast addition of 5 to view_b
view_b += 5

# Display the modified view_b and the original array_a to observe the effect
print("\nModified view b:\n", view_b)
print("Original array_a after modification:\n", array_a)


Original array_a:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
View b:
 [[ 5  6]
 [ 8  9]
 [11 12]]

Modified view b:
 [[10 11]
 [13 14]
 [16 17]]
Original array_a after modification:
 [[ 1  2  3]
 [ 4 10 11]
 [ 7 13 14]
 [10 16 17]]


QUe.79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view
`reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it
reflects changes in the original `orig_array`.




In [84]:
import numpy as np

# Create a NumPy array 'orig_array' of shape (2, 4) with values from 1 to 8
orig_array = np.arange(1, 9).reshape(2, 4)

# Create a reshaped view 'reshaped_view' of shape (4, 2)
reshaped_view = orig_array.reshape(4, 2)

# Display the original array and reshaped view before modification
print("Original array (orig_array):\n", orig_array)
print("Reshaped view (reshaped_view):\n", reshaped_view)

# Modify an element in 'reshaped_view'
reshaped_view[2, 1] = 99

# Display the modified reshaped view and the original array to observe changes
print("\nModified reshaped view (reshaped_view):\n", reshaped_view)
print("Original array (orig_array) after modification:\n", orig_array)


Original array (orig_array):
 [[1 2 3 4]
 [5 6 7 8]]
Reshaped view (reshaped_view):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Modified reshaped view (reshaped_view):
 [[ 1  2]
 [ 3  4]
 [ 5 99]
 [ 7  8]]
Original array (orig_array) after modification:
 [[ 1  2  3  4]
 [ 5 99  7  8]]


Que.80) Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of
elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

In [85]:
import numpy as np

# Create a NumPy array 'data' of shape (3, 4) with random integers between 1 and 10
data = np.random.randint(1, 11, size=(3, 4))

# Extract a copy of elements greater than 5
data_copy = data[data > 5].copy()

# Display the original data and data_copy before modification
print("Original data:\n", data)
print("Data copy (elements > 5):\n", data_copy)

# Modify an element in 'data_copy'
data_copy[0] = 99

# Display the modified data_copy and the original data to check if the change is reflected
print("\nModified data_copy:\n", data_copy)
print("Original data after modification:\n", data)


Original data:
 [[ 7  5 10  6]
 [10  6 10  7]
 [ 6  9  2  4]]
Data copy (elements > 5):
 [ 7 10  6 10  6 10  7  6  9]

Modified data_copy:
 [99 10  6 10  6 10  7  6  9]
Original data after modification:
 [[ 7  5 10  6]
 [10  6 10  7]
 [ 6  9  2  4]]


Que.81)81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction
operations between them.

In [86]:
import numpy as np

# Create two matrices A and B with identical shapes containing integers
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Perform addition and subtraction between matrices A and B
addition_result = A + B
subtraction_result = A - B

# Display the results
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("\nAddition of A and B:\n", addition_result)
print("\nSubtraction of A and B:\n", subtraction_result)


Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]

Addition of A and B:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]

Subtraction of A and B:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


Que.82.  Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

In [87]:
import numpy as np

# Create matrix C of shape (3x2)
C = np.array([[1, 2], [3, 4], [5, 6]])

# Create matrix D of shape (2x4)
D = np.array([[7, 8, 9, 10], [11, 12, 13, 14]])

# Perform matrix multiplication (C @ D or np.dot(C, D))
result = np.dot(C, D)

# Display the matrices and the result
print("Matrix C (3x2):\n", C)
print("Matrix D (2x4):\n", D)
print("\nMatrix multiplication result (3x4):\n", result)


Matrix C (3x2):
 [[1 2]
 [3 4]
 [5 6]]
Matrix D (2x4):
 [[ 7  8  9 10]
 [11 12 13 14]]

Matrix multiplication result (3x4):
 [[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]]


que.83. Create a matrix `E` and find its transpose.

In [88]:
import numpy as np

# Create matrix E
E = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Find the transpose of matrix E
E_transpose = E.T

# Display the original matrix and its transpose
print("Matrix E:\n", E)
print("\nTranspose of Matrix E:\n", E_transpose)


Matrix E:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Transpose of Matrix E:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


Que.84. Generate a square matrix `F` and compute its determinant.

In [89]:
import numpy as np

# Create a square matrix F (3x3 matrix for example)
F = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Compute the determinant of matrix F
det_F = np.linalg.det(F)

# Display the matrix and its determinant
print("Matrix F:\n", F)
print("\nDeterminant of Matrix F:", det_F)


Matrix F:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Determinant of Matrix F: 0.0


Que.85. Create a square matrix `G` and find its inverse.

In [90]:
import numpy as np

# Create a square matrix G (3x3 matrix for example)
G = np.array([[4, 7, 2], [3, 5, 1], [2, 6, 8]])

# Compute the inverse of matrix G
G_inv = np.linalg.inv(G)

# Display the matrix and its inverse
print("Matrix G:\n", G)
print("\nInverse of Matrix G:\n", G_inv)


Matrix G:
 [[4 7 2]
 [3 5 1]
 [2 6 8]]

Inverse of Matrix G:
 [[-17.   22.    1.5]
 [ 11.  -14.   -1. ]
 [ -4.    5.    0.5]]
